/* Generated By:JJTree: Do not edit this line. ASTatomSequence.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTatomSequence extends SimpleNode {
  public ASTatomSequence(int id) {
    super(id);
  }

  public ASTatomSequence(ElpsTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=75ba7b9f249c9f610f4f2c70d1e14063 (do not edit this line) */
