/* Generated By:JJTree: Do not edit this line. ASTidentifierRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTidentifierRange extends SimpleNode {
  public ASTidentifierRange(int id) {
    super(id);
  }

  public ASTidentifierRange(ElpsTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=03b059418445f196b659cae1028966ff (do not edit this line) */
