/* Generated By:JJTree: Do not edit this line. ASTnumericRange.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTnumericRange extends SimpleNode {
  public ASTnumericRange(int id) {
    super(id);
  }

  public ASTnumericRange(ElpsTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=76f6cb5efd7823f101e0a2e2aaf2b518 (do not edit this line) */
