/* Generated By:JJTree: Do not edit this line. ASTorCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTorCondition extends SimpleNode {
  public ASTorCondition(int id) {
    super(id);
  }

  public ASTorCondition(ElpsTranslator p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=64c1af4b0edcf8b0e55268866f6e7da1 (do not edit this line) */
